

opt_in_rules:
  - empty_count
  - capture_variable
  - convenience_type
  - empty_string
  - fatal_error_message
  - file_name
  - first_where
  - modifier_order
  - toggle_bool
  - fallthrough
  - identical_operands
  - joined_default_parameter
  - unavailable_function
  - overridden_super_call
  - anyobject_protocol
  - array_init
  - block_based_kvo
  - class_delegate_protocol
  - closure_body_length
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_object_literal
  - discouraged_optional_boolean
  - empty_collection_literal
  - empty_xctest_method
  - enum_case_associated_values_count
  - explicit_init
  - file_header
  - file_name_no_space
  - flatmap_over_map_reduce
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - legacy_random
  - let_var_whitespace
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - no_extension_access_modifier
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  - operator_usage_whitespace
  - optional_enum_case_matching
  - override_in_extension
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  - private_subject
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - unused_declaration
  - unused_import
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition
  - implicit_return
  - explicit_top_level_acl
#  - force_unwrapping # TODO TURN THIS ON!
#  - type_contents_order # turn on later??
#  - expiring_todo


# rejected rules
#  - file_types_order
#  - raw_value_for_camel_cased_codable_enum
#  - discouraged_optional_collection
#  - indentation_width # don't like
#  - missing_docs # this would be great, but zero files have docs
#  - multiline_arguments_brackets # don't like
#  - multiline_parameters_brackets # don't like
#  - no_grouping_extension # don't like
#  - object_literal # no
#  - prohibited_interface_builder # no
#  - required_deinit # no
#  - strict_fileprivate # no
#  - extension_access_modifier # no, I prefer specifying contents of extension's access
#  - explicit_type_interface # no, this is dumb
#  - conditional_returns_on_newline # no
#  - explicit_acl # no
#  - explicit_enum_raw_value # don't like

# Alternatively, specify all rules explicitly by uncommenting this option:
# only_rules: # delete `disabled_rules` & `opt_in_rules` if using this
#   - empty_parameters
#   - vertical_whitespace

#included: # paths to include during linting. `--path` is ignored if present.
#  - Rooster-macOS
#  - Rooster-Shared
#  - Rooster-Core
disabled_rules:
- todo
- cyclomatic_complexity

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Sparkle*
  - Rooster-iOS

analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self

nesting:
  type_level: 2 # up 1 from default
  function_level: 2
  check_nesting_in_closures_and_statements: true
  always_allow_one_type_in_functions: false

force_cast: warning # implicitly

force_try:
  severity: warning # explicitly

line_length:
  warning: 150
  error: 200
  ignores_comments: true
#  ignores_urls: false
#  ignores_function_declarations: false
#  ignores_interpolated_strings: true

type_body_length:
  - 300 # warning
  - 400 # error

file_length:
  warning: 500
  error: 1200

type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
  allowed_symbols: ["_"] # these are allowed in type names

identifier_name:
  min_length: # only min_length
    warning: 2
    error: 2 # only error
  excluded: # excluded via string array
    - i
    - id
    - GlobalAPIKey

reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, codeclimate, junit, html, emoji, sonarqube, markdown, github-actions-logging)
